using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyConfiguration("Release - No Tests")]
[assembly: AssemblyCompany("Paul Kohler")]
[assembly: AssemblyCopyright("Copyright (C) 2005-2015 Paul Kohler")]