//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSqlQuery.Plugins.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniSqlQuery.Plugins.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not populate with current connection string - .
		/// </summary>
		internal static string BindNewConnectionStringBuilder_Could_not_populate_with_current_connection_string___
		{
			get
			{
				return ResourceManager.GetString("BindNewConnectionStringBuilder_Could_not_populate_with_current_connection_string_" +
						"__", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connected to &apos;{0}&apos; successfully..
		/// </summary>
		internal static string Connected_to_0_successfully
		{
			get
			{
				return ResourceManager.GetString("Connected_to_0_successfully", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connection Failed.
		/// </summary>
		internal static string Connection_Failed
		{
			get
			{
				return ResourceManager.GetString("Connection_Failed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connection Successful.
		/// </summary>
		internal static string Connection_Successful
		{
			get
			{
				return ResourceManager.GetString("Connection_Successful", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Failed connecting to &apos;{0}&apos;.{1}{2}.
		/// </summary>
		internal static string Failed_connecting_to_0_1_2
		{
			get
			{
				return ResourceManager.GetString("Failed_connecting_to_0_1_2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save Changes?.
		/// </summary>
		internal static string Save_Changes
		{
			get
			{
				return ResourceManager.GetString("Save_Changes", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table: .
        /// </summary>
        internal static string Table_colon {
            get {
                return ResourceManager.GetString("Table_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table: (none).
        /// </summary>
        internal static string Table_none {
            get {
                return ResourceManager.GetString("Table_none", resourceCulture);
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to The connection details have changed, do you want to save?
		///.
		/// </summary>
		internal static string The_connection_details_have_changed__do_you_want_to_save
		{
			get
			{
				return ResourceManager.GetString("The_connection_details_have_changed__do_you_want_to_save", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data.
        /// </summary>
        internal static string ViewData {
            get {
                return ResourceManager.GetString("ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data Error.
        /// </summary>
        internal static string ViewDataError {
            get {
                return ResourceManager.GetString("ViewDataError", resourceCulture);
            }
        }
    }
}
